### ISSUE TITLE
Unmount Component

### ISSUE THREAD

**Issue by sriram-nappa** [amine7536/react-clockwall#1]
I found a issue when the component is removed from DOM. The component setInterval timer keeps updating the timer state in background even when the component is removed from DOM. I think this is because there is no instance like componentWillUnmount where the component will clear the timer when it is unmounted from the DOM.

**Comment by amine7536** [comment]
Thanks for reporting this issue, i've added a clearInterval in the componentWillUnmout function.
Rgds
Amine
